# Generated by Django 5.1.1 on 2024-09-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medico', models.CharField(max_length=200)),
                ('especializacao', models.CharField(max_length=200)),
                ('crm', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=11)),
            ],
        ),
    ]
